// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
 
let package = Package(
    name: "llm.swift",
    products: [
        .library(
            name: "llm.swift",
            targets: ["llm.swift"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Bouke/Glob.git", "1.0.5"..<"2.0.0")
    ],
    targets: [
        .target(
            name: "llm.swift",
            dependencies: [
                "Glob",
            ],
            path: ".",
            sources: [
                "llmc",
                "dev/metal",
                "LaunchPad.swift",
                "test_gpt2.swift",
                "train_gpt2.swift",
            ]),
    ]
)
